version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: seo-tech-check-backend
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - SCRAPE_DO_API_KEY=ef8324bc40db40949fd2819c8338c2ea0d9573d2940
      - LOG_LEVEL=info
      - ENABLE_RATE_LIMITING=true
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX_REQUESTS=100
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - seo-tech-check-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: seo-tech-check-frontend
    environment:
      - REACT_APP_API_URL=http://backend:3001/api
      - NODE_ENV=development
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - seo-tech-check-network
    restart: unless-stopped

networks:
  seo-tech-check-network:
    driver: bridge

volumes:
  node_modules:
